import type { AchievementDef } from '../engine/types';

/**
 * ACHIEVEMENTS
 *
 * Mix of "did a stupid thing", "did a hard thing", and "did a thing almost
 * nobody does". Conditions are evaluated after every resolution.
 */
export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'ach_bad_idea',
    name: 'BAD IDEA',
    desc: 'Make your first genuinely terrible decision.',
    icon: '💀',
    when: { run: { highRiskChoices: [1, null] } },
  },
  {
    id: 'ach_chaos_agent',
    name: 'CHAOS AGENT',
    desc: 'Trigger 20 high-risk outcomes.',
    icon: '🌪️',
    when: { run: { highRiskOutcomes: [20, null] } },
  },
  {
    id: 'ach_youre_fired',
    name: "YOU'RE FIRED",
    desc: 'Lose three jobs.',
    icon: '📦',
    when: { run: { timesFired: [3, null] } },
  },
  {
    id: 'ach_capitalist',
    name: 'CAPITALIST',
    desc: 'Found three businesses.',
    icon: '🏭',
    when: { run: { businessesFounded: [3, null] } },
  },
  {
    id: 'ach_how_did_this_work',
    name: 'HOW DID THIS WORK?',
    desc: 'Turn a ridiculous idea into a real business.',
    icon: '🤷',
    when: { run: { businessesFounded: [1, null] }, stats: { career: [60, 100] }, minNetWorth: 300_000 },
  },
  {
    id: 'ach_love_hurts',
    name: 'LOVE HURTS',
    desc: 'Experience three breakups.',
    icon: '💔',
    when: { run: { breakups: [3, null] } },
  },
  {
    id: 'ach_diamond_hands',
    name: 'DIAMOND HANDS',
    desc: 'Hold an investment through a crash.',
    icon: '💎',
    when: { has: ['heldTheCrash'] },
  },
  {
    id: 'ach_mom_was_right',
    name: 'MOM WAS RIGHT',
    desc: 'Ignore your family and live to regret it.',
    icon: '📞',
    when: { has: ['refusedSibling'], stats: { happiness: [0, 45] } },
  },
  {
    id: 'ach_one_percent',
    name: 'ONE PERCENT',
    desc: 'Reach a $10M net worth.',
    icon: '🥂',
    when: { minNetWorth: 10_000_000 },
  },
  {
    id: 'ach_billionaire',
    name: 'THREE COMMAS',
    desc: 'Reach a $1B net worth.',
    icon: '🚀',
    secret: true,
    when: { minNetWorth: 1_000_000_000 },
  },
  {
    id: 'ach_homeowner',
    name: 'PROPERTY OWNER',
    desc: 'Buy a home.',
    icon: '🏠',
    when: { run: { propertiesBought: [1, null] } },
  },
  {
    id: 'ach_tycoon',
    name: 'TYCOON',
    desc: 'Buy three properties.',
    icon: '🏘️',
    when: { run: { propertiesBought: [3, null] } },
  },
  {
    id: 'ach_married',
    name: 'SETTLED',
    desc: 'Get married.',
    icon: '💍',
    when: { partner: ['married'] },
  },
  {
    id: 'ach_parent',
    name: 'RESPONSIBLE ADULT',
    desc: 'Become a parent.',
    icon: '👶',
    when: { children: [1, 20] },
  },
  {
    id: 'ach_wealthy_exit',
    name: 'EXIT',
    desc: 'Sell a company.',
    icon: '✍️',
    when: { run: { businessesSold: [1, null] } },
  },
  {
    id: 'ach_ceo',
    name: 'THE CORNER OFFICE',
    desc: 'Reach the top of your career path.',
    icon: '🪑',
    when: { career: { level: [6, 9] } },
  },
  {
    id: 'ach_boundaries',
    name: 'SAID NO',
    desc: 'Set a boundary at work and survive it.',
    icon: '🚪',
    when: { has: ['setBoundary'] },
  },
  {
    id: 'ach_evidence',
    name: 'PAPER TRAIL',
    desc: 'Document everything and let it play out.',
    icon: '📁',
    when: { has: ['hasPaperTrail'] },
  },
  {
    id: 'ach_therapy',
    name: 'DOING THE WORK',
    desc: 'Start therapy.',
    icon: '🛋️',
    when: { has: ['inTherapy'] },
  },
  {
    id: 'ach_sober',
    name: 'CLEAR HEADED',
    desc: 'Take three months off the booze.',
    icon: '🍵',
    when: { has: ['soberCurious'] },
  },
  {
    id: 'ach_sabbatical',
    name: 'GAP YEAR, AGE 31',
    desc: 'Take a proper break from work.',
    icon: '🎒',
    when: { has: ['sabbatical'] },
  },
  {
    id: 'ach_broke',
    name: 'COMPLETELY BROKE',
    desc: 'Hit zero dollars with nothing behind it.',
    icon: '🕳️',
    when: { flags: { timesBroke: [2, null] } },
  },
  {
    id: 'ach_denied',
    name: 'COULDN’T HAVE SAID IT BETTER',
    desc: 'Deny everything to HR.',
    icon: '🤐',
    secret: true,
    when: { has: ['deniedToHR'] },
  },
  {
    id: 'ach_three_jobs',
    name: 'MULTIPLE HATS',
    desc: 'Hold four different jobs in one life.',
    icon: '🎩',
    when: { run: { decisionsMade: [0, null] } },
    counter: { key: 'jobChanges', gte: 4 },
  },
  {
    id: 'ach_family_anchor',
    name: 'THE RESPONSIBLE ONE',
    desc: 'Carry your family through something hard.',
    icon: '⚓',
    when: { flags: { familySupport: [2, null] } },
  },
  {
    id: 'ach_retired_early',
    name: 'OUT BEFORE FORTY',
    desc: 'Stop working before you turn 40.',
    icon: '🏖️',
    when: { flags: { retired: [1, null] }, age: [0, 40] },
  },
  {
    id: 'ach_kind',
    name: 'GOOD ONE',
    desc: 'Make ten genuinely kind decisions.',
    icon: '🤝',
    when: { stats: { karma: [85, 100] } },
  },
  {
    id: 'ach_lucky',
    name: 'SUSPICIOUSLY LUCKY',
    desc: 'Win something absurd.',
    icon: '🎰',
    when: { has: ['lotteryBigWin'] },
  },
  {
    id: 'ach_founder_twice',
    name: 'GLUTTON FOR PUNISHMENT',
    desc: 'Found a second business after the first one ended.',
    icon: '🔁',
    when: { run: { businessesFounded: [2, null] } },
  },
  {
    id: 'ach_full_album',
    name: 'LIVED A LOT',
    desc: 'Make 100 decisions in a single life.',
    icon: '📖',
    when: { run: { decisionsMade: [100, null] } },
  },
  {
    id: 'ach_deep_end',
    name: 'TO THE END',
    desc: 'Reach age 80 in a life.',
    icon: '🕰️',
    when: { age: [80, 200] },
  },
  {
    id: 'ach_stress_test',
    name: 'STRESS TEST',
    desc: 'Peak stress above 95% and keep going.',
    icon: '🫀',
    when: { stats: { stress: [95, 100] } },
  },
  {
    id: 'ach_balance',
    name: 'ACTUALLY BALANCED',
    desc: 'Past 60 in every primary stat at the same time.',
    icon: '⚖️',
    when: {
      stats: {
        career: [60, 100],
        happiness: [60, 100],
        relationships: [60, 100],
        reputation: [60, 100],
        stress: [0, 45],
      },
      age: [35, 200],
    },
  },
  {
    id: 'ach_multi_hat',
    name: 'CHANGED MY MIND',
    desc: 'Change career path entirely.',
    icon: '🧭',
    when: { has: ['retrained'] },
  },
  {
    id: 'ach_bad_landlord',
    name: 'RENT SEEKER',
    desc: 'Own property you do not live in.',
    icon: '🔑',
    when: { has: ['landlord'], minNetWorth: 200_000 },
  },
];
