import type { EndingDef } from '../engine/types';

/**
 * ENDINGS
 *
 * Every ending is a `when` clause, evaluated top-down by priority after each
 * resolution. The highest-priority match wins, so the most specific and most
 * earned endings are listed first.
 *
 * A run almost always ends one of three ways: a hard-condition ending fires
 * early (retire at 35, sell for millions), the player reaches MAX_AGE, or a
 * catastrophic event ends things early.
 */
export const ENDINGS: EndingDef[] = [
  /* ------------------------------------------------------- wealth extremes */
  {
    id: 'ending_billionaire',
    title: 'BILLIONAIRE',
    final: true,
    rarity: 'legendary',
    priority: 100,
    blurb: 'You did it. Nobody is entirely sure you should have.',
    body: 'There is a magazine profile and a photograph in which you are standing in front of a building you own, looking slightly confused, which is how you have looked in every photograph since the number passed a certain size.',
    flavour: 'You made a billion dollars. You still check the price of a sandwich.',
    art: 'ending_billionaire',
    when: { minNetWorth: 1_000_000_000 },
  },
  {
    id: 'ending_one_percent',
    title: 'MILLIONAIRE',
    final: true,
    rarity: 'rare',
    priority: 92,
    blurb: 'Rich, quietly. Which is the good kind.',
    body: 'It did not arrive all at once. It arrived in increments, at four different moments across twenty years, and each time you did the sensible thing rather than the exciting one. You have a financial advisor who is genuinely fond of you.',
    flavour: 'Eight figures and a genuinely boring portfolio.',
    art: 'ending_rich',
    when: { minNetWorth: 10_000_000 },
  },
  {
    id: 'ending_comfortable',
    title: 'COMFORTABLE',
    final: true,
    rarity: 'common',
    priority: 40,
    blurb: 'Not rich. Not worried. Genuinely rarer than rich.',
    body: 'You have a house, a pension, a small amount of money that does something in the background, and no specific financial fear. When people ask how you are, you have started answering honestly.',
    flavour: 'You are going to be fine, and you know it, which is the whole prize.',
    art: 'ending_comfortable',
    when: { minNetWorth: 750_000, stats: { stress: [0, 60] }, flags: { retired: [1, null] } },
  },

  /* ------------------------------------------------------------- the exits */
  {
    id: 'ending_retired_35',
    title: 'RETIRED AT 35',
    rarity: 'legendary',
    priority: 96,
    blurb: 'You stopped. On purpose. While it was still going well.',
    body: 'You did the arithmetic at a kitchen table, realised the number worked, and handed in your notice on a Wednesday. For eight months you did not know what to do with your hands. Then you learned.',
    flavour: 'Everyone said you would be bored. Everyone was wrong.',
    art: 'ending_retired',
    when: {
      age: [34, 40],
      minNetWorth: 1_600_000,
      stats: { stress: [0, 55] },
      flags: { retired: [1, null] },
    },
  },
  {
    id: 'ending_early_retirement',
    title: 'EARLY RETIREMENT',
    final: true,
    rarity: 'rare',
    priority: 70,
    blurb: 'You got out before the building ate you.',
    body: 'At 52 you stopped working and discovered that most of what you called a personality was actually a job. It took a year to find out who was underneath, and the person underneath is quieter and better company.',
    flavour: 'Fifty-two, and the alarm is off permanently.',
    art: 'ending_retired',
    when: { age: [48, 62], minNetWorth: 900_000, flags: { retired: [1, null] } },
  },
  {
    id: 'ending_workaholic',
    title: 'WORKAHOLIC',
    final: true,
    rarity: 'uncommon',
    priority: 66,
    blurb: 'You won. Look at what you won.',
    body: 'The title is enormous and the office has your name on the door and you have not had a holiday in four years that did not involve a laptop. Your partner left in March. You would describe the last decade as "productive."',
    flavour: 'You never took a day off. Not one you enjoyed.',
    art: 'ending_workaholic',
    when: {
      age: [42, 84],
      stats: { career: [88, 100], stress: [80, 100], relationships: [0, 35] },
    },
  },
  {
    id: 'ending_corporate_legend',
    title: 'CORPORATE LEGEND',
    final: true,
    rarity: 'rare',
    priority: 68,
    blurb: 'You went all the way up, and you stayed a person.',
    body: 'Chief something. Twenty-nine years. You hired people and you remembered their names and you fired almost nobody. At your leaving drinks, four separate people said the same sentence about you, which is the finest eulogy a career can have.',
    flavour: 'You reached the top floor without becoming the top floor.',
    art: 'ending_corporate',
    when: { career: { level: [5, 9] }, stats: { career: [85, 100], reputation: [60, 100], relationships: [55, 100] } },
  },
  {
    id: 'ending_accidental_ceo',
    title: 'ACCIDENTAL CEO',
    final: true,
    rarity: 'rare',
    priority: 72,
    blurb: 'You did not plan this. You are not sure anyone did.',
    body: 'You were the person who was in the room, and then you were the person who knew the thing, and then suddenly there were sixty people and a board and a strategy document with your name on the cover. You have been faking it competently for eleven years.',
    flavour: 'Nobody is more surprised than you. Nobody.',
    art: 'ending_ceo',
    when: {
      age: [36, 84],
      businesses: { count: [1, 9] },
      stats: { reputation: [72, 100], career: [75, 100] },
      flags: { soleOwner: [1, null] },
    },
  },

  /* --------------------------------------------------------- entrepreneurs */
  {
    id: 'ending_serial_entrepreneur',
    title: 'SERIAL ENTREPRENEUR',
    final: true,
    rarity: 'rare',
    priority: 64,
    blurb: 'Three businesses. Two failures. One that worked.',
    body: 'You have started something in every decade of your adult life and you have learned precisely nothing from any of them, in the sense that you would do all of it again tomorrow, which is the actual definition of the type.',
    flavour: 'Your LinkedIn says "Founder". Your tax returns say "God help us".',
    art: 'ending_entrepreneur',
    when: { run: { businessesFounded: [3, null] } },
  },
  {
    id: 'ending_startup_sold',
    title: 'FOUNDER, EXITED',
    final: true,
    rarity: 'rare',
    priority: 74,
    blurb: 'You built it, you sold it, you are not sure you would do it again.',
    body: 'A number, a lawyer, a moment in a glass room, and then a very strange emptiness at about week three. You have the money and you have the story and you have a scar where the thing used to be.',
    flavour: 'The acquisition went well. The bit after it is still being worked out.',
    art: 'ending_founder',
    when: { flags: { soldBig: [1, null] } },
  },
  {
    id: 'ending_startup_disaster',
    title: 'STARTUP DISASTER',
    final: true,
    rarity: 'uncommon',
    priority: 62,
    blurb: 'You raised money. You spent it. It is gone.',
    body: 'The postmortem, written honestly by you at 2am, is genuinely the best thing you have ever produced. Nobody reads postmortems though. They read the other thing, the announcement, and then they move on.',
    flavour: 'The lesson cost eleven months and $40,000. You kept the lesson.',
    art: 'ending_failure',
    when: {
      flags: { startupDying: [1, null] },
      stats: { happiness: [0, 55] },
      businesses: { count: [0, 1] },
    },
  },
  {
    id: 'ending_real_estate_tycoon',
    title: 'REAL ESTATE TYCOON',
    final: true,
    rarity: 'rare',
    priority: 76,
    blurb: 'Bricks, tenants, and a folder of tenancy agreements.',
    body: 'Nine doors. You know every boiler, every tenant, and every date. You are the person people call about damp, and you have become extremely good at it, and you have monetised the living out of a totally unglamorous thing.',
    flavour: 'You never built anything. You just bought carefully.',
    art: 'ending_property',
    when: { businesses: { types: ['real_estate'] }, minNetWorth: 2_000_000 },
  },

  /* ------------------------------------------------------------ the people */
  {
    id: 'ending_family_first',
    title: 'FAMILY FIRST',
    final: true,
    rarity: 'uncommon',
    priority: 58,
    blurb: 'You chose the people. Every single time.',
    body: 'You turned things down. You drove the distance. You were in the corridor and you were at the game and you were on the phone at 6am. Your career is smaller than it could have been and your table is full.',
    flavour: 'Nobody at your funeral will mention your job title.',
    art: 'ending_family',
    when: {
      age: [45, 84],
      stats: { relationships: [78, 100], happiness: [65, 100] },
      children: [1, 12],
      partner: ['married'],
    },
  },
  {
    id: 'ending_quiet_life',
    title: 'QUIET LIFE',
    final: true,
    rarity: 'uncommon',
    priority: 44,
    blurb: 'Nothing happened. Beautifully.',
    body: 'A steady job that you were good at, a person you liked, a dog nobody planned, and a house that is genuinely quiet in the evenings. You never went viral, you were never rich, and you were, on almost every day, content.',
    flavour: 'No chaos. No catastrophe. Just a life.',
    art: 'ending_quiet',
    when: { age: [50, 84], stats: { stress: [0, 42], happiness: [62, 100] }, flags: { quietLife: [1, null] } },
  },
  {
    id: 'ending_broke_but_happy',
    title: 'BROKE BUT HAPPY',
    final: true,
    rarity: 'uncommon',
    priority: 54,
    blurb: 'The money never showed up. You were fine.',
    body: 'You rented forever, you never had a pension worth the name, and you have genuinely had a better time than most of the people who did. You have stories. You have friends. You have a specific laugh that people remember.',
    flavour: 'The bank says no. The people say yes.',
    art: 'ending_happy',
    when: { stats: { happiness: [72, 100] }, maxNetWorth: 400_000, age: [55, 200] },
  },
  {
    id: 'ending_love_hurts',
    title: 'TWO DIVORCES AND A GOOD SONG',
    final: true,
    rarity: 'uncommon',
    priority: 50,
    blurb: 'You loved. Repeatedly. Expensively.',
    body: 'Two marriages, one genuinely great decade in the middle, and a habit of choosing people who were exciting for about eighteen months. You are on excellent terms with one ex and no terms at all with the other.',
    flavour: 'You did not get it right. You did get it.',
    art: 'ending_romance',
    when: { run: { breakups: [3, null] } },
  },
  {
    id: 'ending_alone_not_lonely',
    title: 'UNATTACHED',
    final: true,
    rarity: 'common',
    priority: 46,
    blurb: 'You stayed single, and it was entirely a choice.',
    body: 'You never married and never wanted the version of it you were shown. You have friends you have kept for thirty years a good flat a good dog and full control of the remote. You are not sad and you are tired of being asked about it.',
    flavour: 'On your own. Not by accident.',
    art: 'ending_solo',
    when: { age: [50, 84], partner: ['single'], stats: { happiness: [55, 100], relationships: [55, 100] } },
  },

  /* --------------------------------------------------------------- chaos */
  {
    id: 'ending_internet_celebrity',
    title: 'INTERNET CELEBRITY',
    final: true,
    rarity: 'rare',
    priority: 60,
    blurb: 'Famous. Of the specific, modern kind.',
    body: 'Two million followers and a genuine business built on being recognisable. Nobody in your family understands what you do, and the ones over fifty think it is a phase. It pays better than anything else you have ever done and it could end on any Thursday.',
    flavour: 'You are famous for something you would have to explain.',
    art: 'ending_famous',
    when: { stats: { reputation: [88, 100] }, flags: { wentViral: [1, null] }, minCash: 60_000 },
  },
  {
    id: 'ending_world_traveller',
    title: 'WORLD TRAVELLER',
    final: true,
    rarity: 'uncommon',
    priority: 56,
    blurb: 'Forty-one countries and no fixed address.',
    body: 'You stopped accumulating things in your early thirties and started accumulating stamps. You have slept in eleven ports, four deserts and a monastery, and you have a genuinely calibrated sense of what a person actually needs.',
    flavour: 'You own one suitcase and you know where the handles are worn.',
    art: 'ending_traveler',
    when: { flags: { sabbatical: [1, null] }, stats: { happiness: [60, 100] } },
  },
  {
    id: 'ending_debt_king',
    title: 'DEBT KING',
    final: true,
    rarity: 'uncommon',
    priority: 80,
    blurb: 'You owe a genuinely impressive amount of money.',
    body: 'Three consolidations, two credit lines and one arrangement you do not fully understand with a man whose name you have written down in a notebook. You have never once been bankrupt, which is a technical achievement you are not sure counts.',
    flavour: 'You never got rich. You just never stopped owing.',
    art: 'ending_debt',
    when: { debt: [65_000, null], maxNetWorth: 250_000 },
  },
  {
    id: 'ending_fired_again',
    title: 'FIRED AGAIN',
    final: true,
    rarity: 'uncommon',
    priority: 78,
    blurb: 'Four jobs in six years. Impressive, honestly.',
    body: 'Each one ended for a different reason and each reason had the same shape. You are extremely talented and completely unwilling to be managed, and the combination has cost you a genuinely enormous amount of money.',
    flavour: 'You were always right. You were also always unemployed.',
    art: 'ending_fired',
    when: { run: { timesFired: [3, null] }, stats: { career: [0, 55] } },
  },
  {
    id: 'ending_living_with_parents',
    title: 'BACK IN THE SPARE ROOM',
    /* aka LIVING WITH PARENTS */
    final: true,
    rarity: 'common',
    priority: 82,
    blurb: 'It was meant to be temporary. Living with your parents never is.',
    body: 'It started as a money thing. Then it was a health thing. You are forty-four and you are extremely careful about the volume of the television after 22:00, and your mother is genuinely happy to have you and that is the part that is hardest to hold.',
    flavour: 'The room still has your school photos in it.',
    art: 'ending_parents',
    when: { age: [36, 60], homeTier: ['parents_couch'] },
  },

  /* --------------------------------------------------------------- health */
  {
    id: 'ending_health_scare',
    title: 'THE WARNING',
    final: true,
    rarity: 'uncommon',
    priority: 88,
    blurb: 'It happened at 44. You were lucky.',
    body: 'A hospital, four days, and a consultant who did not soften anything. You were given a warning rather than an ending, and you took it completely seriously for eleven months, and then mostly seriously after that.',
    flavour: 'You got a second half. Not everybody does.',
    art: 'ending_health',
    when: { age: [40, 70], stats: { health: [0, 40] } },
  },
  {
    id: 'ending_long_good_life',
    title: 'A LONG GOOD LIFE',
    final: true,
    rarity: 'common',
    priority: 30,
    blurb: 'You got old. That was the goal, and it was harder than it sounds.',
    body: 'Eighty-four. A life with genuine damage in it and genuine repair in it. You outlived one friend, one dog and two of your own opinions, and the last decade was quieter and better than anyone predicted.',
    flavour: 'You made it all the way.',
    art: 'ending_longlife',
    when: { age: [80, 200] },
  },

  /* -------------------------------------------------------------- triggered */
  {
    id: 'ending_ruin',
    title: 'FINANCIAL RUIN',
    rarity: 'uncommon',
    priority: 98,
    blurb: 'It caught up. All of it, at once.',
    body: 'The letters have a sequence now and the phone calls have a pattern and there is a specific tone that people use when they have been told to be firm. You did not lose it in one decision. You lost it in eleven, over nine years, and each one made sense at the time.',
    flavour: 'You were always going to be fine. Right up until you were not.',
    art: 'ending_ruin',
    when: {
      debt: [95_000, null],
      stats: { stress: [72, 100] },
      maxNetWorth: -60_000,
      age: [34, 200],
      career: { employed: false },
    },
  },

  /* ------------------------------------------------------------- fallbacks */
  {
    id: 'ending_survivor',
    title: 'STILL HERE',
    final: true,
    rarity: 'common',
    priority: 20,
    blurb: 'You did not win. You did not lose. You kept going.',
    body: 'Decade after decade of ordinary, load-bearing decisions. Nothing that makes a story, and everything that makes a life.',
    flavour: 'The most common ending, and the most underrated.',
    art: 'ending_survivor',
    when: {},
  },
  {
    id: 'ending_final_chapter',
    title: 'THE FINAL CHAPTER',
    final: true,
    rarity: 'common',
    priority: 2,
    blurb: 'The clock ran out on a genuinely eventful life.',
    body: 'A run with catastrophes in it and recoveries after them. The summary below is the honest version.',
    flavour: 'You lived it. Now look at it.',
    art: 'ending_final',
    when: { age: [82, 200] },
  },
];
